import { useCallback } from "react"

export const clienteModel = {

    pessoaId: null,
    codigoInterno: null,
    pessoaTipoPessoa: null,
    pessoaRazaoSocial: null,
    pessoaNomeFantasia: null,
    pessoaCnpjCpf: null,
    pessoaTenant: null,
    pessoaIdentidade: null,
    pessoaOrgaoExpedidor: null,
    pessoaDataNascimento: null,
    pessoaCnpj: null,
    pessoaInscricaoEstadual: null,
    pessoaInscricaoMunicipal: null,
    pessoaStatus: null,
    pessoaEnderecos: [],
    pessoaTelefones: [],
    pessoaEnderecosWeb: [],
    clienteEquipamentos: [],
    caminhoImagem: null,
    nomeImagem: null,
    tamanhoImagem: null,
    tipoCliente: null,
    tipoFornecedor: null,
    clientePlanoContaId: null,
    clientePlanoContaDescricao: null,
    clienteTenant: null,
    clienteConsumidorFinal: null,
    clienteRetencaoIr: null,
    clienteVendaSemCadastro: null,
    clienteId: null,
    clienteStatus: null,
    clienteGrupoTributoClienteId: null,
    clienteGrupoTributoClienteDescricao: null,
    clienteGrupoTributoDevolucaoId: null,
    clienteGrupoTributoDevolucaoDescricao: null,
    clienteListaPrecoId: null,
    clienteListaPrecoDescricao: null,
    clienteVendedorInternoId: null,
    clienteVendedorInternoNomeFantasia: null,
    clienteVendedorExternoId: null,
    clienteVendedorExternoNomeFantasia: null,
    clienteRamoAtividadeId: null,
    clienteRamoAtividadeDescricao: null,
    clienteLimiteCredito: null,
    clienteSaldoCredito: null,
    clienteValorMensalidade: null,
    clienteDataPrimeiroBoleto: null,
    clienteConceitoId: null,
    clienteConceitoDescricao: null,
    observacao: null

}


export const pessoaEnderecosModel = {
    bairro: null,
    cep: null,
    cidade: null,
    codigoIbge: null,
    complemento: null,
    id: null,
    logradouro: null,
    numero: null,
    tenant: null,
    tipoEndereco: null,
    uf: null,
}

export const pessoaTelefonesModel = {
    fone: null,
    id: null,
    observacao: null,
    tenant: null,
    tipoTelefoneId: 44,
    tipoTelefonePadrao: true,

}

export const pessoaEnderecosWebModel = {
    endereco: null,
        id: null,
        observacao: null,
        tenant: null,
        tipoWebId: 17,
        tipoWebPadrao: true,
}


export const clienteModel2 = {
    caminhoImagem: null,
    clienteConceitoId: null,
    clienteConsumidorFinal: undefined,
    clienteDataPrimeiroBoleto: null,
    clienteFormaPagamentoId: 52,
    clienteGrupoTributoClienteId: 48,
    clienteGrupoTributoDevolucaoId: null,
    clienteId: null,
    clienteLimiteCredito: undefined,
    clienteListaPrecoId: 44,
    clientePlanoContaId: 108,
    clienteRamoAtividadeId: null,
    clienteRetencaoIr: undefined,
    clienteSaldoCredito: undefined,
    clienteSituacaoId: 29,
    clienteStatus: null,
    clienteTenant: null,
    clienteValorMensalidade: null,
    clienteVendaSemCadastro: undefined,
    clienteVendedorExternoId: null,
    clienteVendedorInternoId: null,
    codigoInterno: null,
    fornecedorAtualizaPreco: null,
    fornecedorGrupoTributoFornecedorId: null,
    fornecedorId: null,
    fornecedorPlanoContaId: null,
    fornecedorStatus: null,
    fornecedorTenant: null,
    id: null,
    observacao: null,
    pessoaCnpj: null,
    pessoaCnpjCpf: null,
    pessoaEnderecos: {

        bairro: null,
        cep: null,
        cidade: null,
        codigoIbge: '',
        complemento: '',
        id: null,
        logradouro: null,
        numero: null,
        tenant: null,
        tipoEndereco: "P",
        uf: null,
    },

    pessoaEnderecosWeb: {

        endereco: null,
        id: null,
        observacao: null,
        tenant: null,
        tipoWebId: 17,
        tipoWebPadrao: true,
    },

    pessoaId: null,
    pessoaIdentidade: undefined,
    pessoaInscricaoEstadual: null,
    pessoaInscricaoMunicipal: null,
    pessoaNomeFantasia: null,
    pessoaOrgaoExpedidor: undefined,
    pessoaRazaoSocial: null,
    pessoaStatus: null,

    pessoaTelefones: {
        fone: null,
        id: null,
        observacao: null,
        tenant: null,
        tipoTelefoneId: 44,
        tipoTelefonePadrao: true,
    },

    pessoaTenant: null,
    pessoaTipoPessoa: "J",
    status: null,
    tamanhoImagem: null,
    tenant: null,
    tipoCliente: true,
    tipoFornecedor: false,
};
